#server:
#  port: 9001
#spring:
#  application:
#    name: cloud-user
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://****:3306/cloud-user?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ****
#    password: ****
#    hikari:
#      minimum-idle: 5
#      idle-timeout: 18000
#      maximum-pool-size: 10
#      auto-commit: true
#      connection-timeout: 30000
#      connection-test-query: select 1
#  cloud:
#    nacos:
#      server-addr: 127.0.0.1:8848
#      discovery:
#        namespace: 805a3a84-bd5e-4ffa-ac3b-03b05202d43e
#        cluster-name: NANJING
#        ephemeral: true
#    sentinel:
#      datasource:
#        test:
#          flow:
#            nacos:
#              server-addr: localhost:8848
#              dataId: ${spring.application.name}-flow-rules
#              groupId: SENTINEL_GROUP
#              rule-type: flow
#          degrade:
#            nacos:
#              server-addr: localhost:8848
#              dataId: ${spring.application.name}-degrade-rules
#              groupId: SENTINEL_GROUP
#              rule-type: degrade
#          system:
#            nacos:
#              server-addr: localhost:8848
#              dataId: ${spring.application.name}-system-rules
#              groupId: SENTINEL_GROUP
#              rule-type: system
#          authority:
#            nacos:
#              server-addr: localhost:8848
#              dataId: ${spring.application.name}-authority-rules
#              groupId: SENTINEL_GROUP
#              rule-type: authority
#          param-flow:
#            nacos:
#              server-addr: localhost:8848
#              dataId: ${spring.application.name}-param-flow-rules
#              groupId: SENTINEL_GROUP
#              rule-type: param-flow
#mybatis:
#  mapperLocations: classpath*:mapper/*.xml
#  typeAliasesPackage: club.comm
#actuator 监控 开放所有页面节点  默认只开启了health、info两个节点
##management:
##  endpoints:
##    web:
##      exposure:
##        include: '*'
##feign:
##  sentinel:
##    enabled: true