#server:
#  port: 9002
#spring:
#  application:
#    name: cloud-goods
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://****:3306/cloud-goods?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ****
#    password: ****
#    hikari:
#      minimum-idle: 5
#      idle-timeout: 18000
#      maximum-pool-size: 10
#      auto-commit: true
#      connection-timeout: 30000
#      connection-test-query: select 1
#  cloud:
#    nacos:
#      server-addr: 127.0.0.1:8848
#      discovery:
#        namespace: 805a3a84-bd5e-4ffa-ac3b-03b05202d43e
#        cluster-name: NANJING
#        ephemeral: true
#mybatis:
#  mapperLocations: classpath*:mapper/*.xml
#  typeAliasesPackage: club.sh1nyu